# 智付通測試平台: https://cwww.spgateway.com/
# 信用卡測試卡號: 4000-2211-2222-2222

default: &default
  merchant_id: MS33470893
  hash_key: 1xPGwF7Ntyqrozd7CupSNhf7LFS0YWC9
  hash_iv: mK0q3ME9laL6LJQX
  url: https://ccore.spgateway.com/MPG/mpg_gateway

development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

production:
  <<: *default